### ISSUE TITLE
/requirements  and /search not accessible with a new install

### ISSUE THREAD

**Issue by k0s** [SMFOSS/CheesePrism#9]
I followed the directions in README.rst to setup a development server with development.ini

I nagivate to http://127.0.0.1:6543/instructions which has a link to http://127.0.0.1:6543/requirements . The latter, however, is a 404

This is also true with /search linked to from the same page

**Comment by k0s** [comment]
see https://github.com/k0s/CheesePrism/commit/3dd42d7786b6f960b49a3bb53b0c5be28a3e6e43 for the fix.  pull request outstanding

**Comment by whitmo** [comment]
merged pull request
